config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'panel/home#index'
  #root to: 'information_requests#index'

  %w(404 422 500 503).each do |code|
    get code, to: 'errors#show', code: code
  end


  resources :information_requests, only: [:index, :create, :new] do
    collection do
      get 'confirm'
      get 'new_personal'
      post 'create_personal'
      get 'please_confirm'
      get 'terms'
    end
  end

  namespace :panel do
    root to: 'home#index'

    resources :profile, only: [:edit, :update]
    resources :versions, only: [:show]

    resources :admin_settings, only: [] do
      put :table_columns, on: :collection
    end

    resources :institution_calendars, only: [:index, :show, :new, :create] do
      resources :calendar_events, except: [:show, :index]
    end

    resources :information_request_iaip_processes

    resources :information_requests do
      member do
        get 'admitted'
        get 'not_admitted'
        put 'process_request'
        get 'closure'
        put 'close_request'
        get 'download_request'
        get 'download_documents'
        put 'admit_date'
        post 'tags'
        get 'edit_personal'
        put 'update_personal'

        resources :information_request_iaip_processes, except: [:index]
      end
      collection do
        put 'updates'
        put 'destroys'
        get 'list'
        get 'get_states'
        get 'statistics'
        get 'basic_csv_export'
        get 'advanced_csv_export'
        get 'new_personal'
        post 'create_personal'
      end

    end

    resources :requirements do
      member do
        put 'management'
      end
    end

    resources :comments

    [
      :institutions,
      :oir_addresses,
      :users,
      :occupations,
      :events,
      :institution_schedules,
      :information_request_records
    ].each do |resource|
      resources resource do
        put :updates, on: :collection
        put :destroys, on: :collection
        get :list, on: :collection
      end
    end
  end

  namespace :api do
    resources :dropdowns do
      member do
        get :state_cities
      end
    end

    resources :information_requests do
      collection do
        get :controls
      end
    end
  end

end

app/controllers/concerns/panel/crud.rb
# frozen_string_literal: true
module Panel
  #
  module Crud
    extend ActiveSupport::Concern

    included do
      respond_to :html
      before_action :set_item, only: [:show, :edit, :update, :destroy]
      before_action :set_uniq_institution!, only: [:update]

      helper_method :model
    end

    def index
      respond_to do |format|
        format.json { super }
        format.csv  { super }
        format.html { respond_to_html }
      end
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'concerns/panel/index'
    end

    def new
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def create
      @item = model.new item_params
      set_uniq_institution!
      return redirect_to(edit_url, flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'concerns/panel/form'
    end

    def update
      respond_to do |format|
        format.json { super }
        format.html do
          return redirect_to(edit_url, flash: { saved: true }) if
            @item.update_attributes(item_params)

          breadcrumbs_for(:edit)
          init_form
          render template: 'concerns/panel/form'
        end
      end
    end

    def destroy
      @item.destroy
      redirect_to index_url, flash: { destroyed: true }
    end

    def init_form
    end

    def set_uniq_institution!
      return unless @item.respond_to? :institution_id
      #return unless current_user.one_institution?
      @item.institution_id = current_user.uniq_institution.try(:id)
    end

    private

    def item_params
      perms = params.require(:item).permit(permits)
      #perms.delete(:institution_id) if current_user.one_institution?
      perms
    end

    def set_item
      @item = if model.respond_to?(:friendly)
                model.friendly.find params[:id]
              else
                model.find params[:id]
              end
    end

    def edit_url
      url_for(action: :edit, id: @item)
    end

    def show_url
      url_for(action: :show, id: @item)
    end

    def index_url
      url_for(controller: model.to_s.underscore.pluralize, action: :index)
    end

    def humanized_model_name(count = 1)
      t(model.to_s.underscore, scope: 'activerecord.models', count: count)
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(count: :many), index_url
      add_breadcrumb t(action.to_s), nil
    end
  end
end

app/controllers/concerns/panel/multiple.rb
# frozen_string_literal: true
module Panel
  #
  module Multiple
    extend ActiveSupport::Concern

    included do
      respond_to :json

      before_action :ngtable_to_rails_filter_param, only: [:index]
      before_action :ngtable_to_rails_sort_param,   only: [:index]
    end

    def update
      respond_to do |format|
        format.html { super }
        format.json do
          sleep 0.5

          return render json: { success: true } if
            @item.update_attributes(item_params)

          render json: { success: false }
        end
      end
    end

    def updates
      model.where(id: params[:ids]).each do |item|
        item.assign_attributes(item_params.to_hash)
        item.save(validate: false)
      end
    end

    def destroys
      model.where(id: params[:ids]).each(&:destroy)
    end

    def index
      respond_to do |format|
        format.html { super }
        format.csv  { super }
        format.json { respond_to_json }
      end
    end

    def respond_to_json
      @q = model.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def json_result(collection)
      {
        result:        json_parsed(collection),
        total_entries: collection.total_entries,
        admin_setting: current_user.admin_setting
      }
    end

    def json_parsed(c)
      c.decorate.as_json(include: json_includes, methods: json_methods)
    end

    def json_includes
      nil
    end

    def json_methods
      nil
    end

    def list
      render json: model
        .select(:id, model.acts_as_label)
        .order(model.acts_as_label)
        .to_json
    end

    private

    def ngtable_to_rails_filter_param
      return unless params.key?(:filter)
      params[:filter]
        .update(params[:filter]) { |_k, v| URI.decode(v) }
        .delete_if { |_k, v| v == 'null' }
    end

    def ngtable_to_rails_sort_param
      return unless params.key?(:sorting)

      params[:filter] ||= {}
      params[:filter][:s] = params[:sorting].flatten.join(' ')
    end
  end
end

app/controllers/panel/admin_settings_controller.rb
# frozen_string_literal: true
module Panel
  #
  class AdminSettingsController < PanelController
    before_action :fetch_admin_setting

    def table_columns
      @admin_setting.update_table_columns(item_params[:table_columns])
    end

    # private

    def item_params
      params.require(:admin_setting).tap do |whitelisted|
        whitelisted[:table_columns] = params[:admin_setting][:table_columns]
      end
    end

    def fetch_admin_setting
      @admin_setting = AdminSetting
                       .where(admin_id: current_admin.id)
                       .first_or_create
    end
  end
end

app/controllers/panel/calendar_events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CalendarEventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      CalendarEvent
    end

    def new
      @institution_calendar = InstitutionCalendar.find(params[:institution_calendar_id])
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/calendar_events/form'
    end

    def edit
      @item = CalendarEvent.find(params[:id])
      @institution_calendar = @item.institution_calendar

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/calendar_events/form'
    end

    def create
      @item = model.new item_params
      @item.user_id = current_user.id
      #@item.institution_calendar_id = params[:institution_calendar_id]
      return redirect_to(edit_panel_institution_calendar_calendar_event_url(@item.institution_calendar_id, @item.id), flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/calendar_events/form'
    end

    def update
      @item = CalendarEvent.find(params[:id])
      @institution_calendar = @item.institution_calendar
      return redirect_to(edit_panel_institution_calendar_calendar_event_url(@item.institution_calendar_id, @item.id), flash: { saved: true }) if @item.update_attributes(item_params)
      init_form
      breadcrumbs_for(:new)
      render template: 'panel/calendar_events/form'
    end

    def destroy
      @item = CalendarEvent.find(params[:id])
      @institution_calendar = @item.institution_calendar
      @item.destroy
      redirect_to panel_institution_calendar_url(@institution_calendar), flash: { destroyed: true }
    end

    def permits
      [:name, :description, :kind, :event_date, :repetitive, :institution_calendar_id]
    end

    def exportable_fields
      [:name]
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'panel/calendar_events/index'
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb "Listado de eventos", panel_institution_calendar_url(params[:institution_calendar_id])
      add_breadcrumb t(action.to_s), nil
    end

  end
end

app/controllers/panel/comments_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CommentsController < PanelController
    include Panel::Crud
    include Panel::Multiple
    load_and_authorize_resource
    skip_before_filter :verify_authenticity_token
    layout false
    respond_to :html, :js

    def model
      Comment
    end

    def permits
      [:message, :document, :requirement_id]
    end

    def exportable_fields
      [:message, :document]
    end

    def new
    end

    def create
      @requirement = Requirement.find(params[:item][:requirement_id])
      @item = model.new item_params
      @item.user_id = current_user.id
      if @item.save
        @users = User.where(id: @requirement.assigned_users) rescue nil
        @users = @users - [current_user] rescue nil
        if @users
          @users.each do |user|
            UserMailer.delay.new_information_request_reply_to_comment(current_user, @item, @requirement, user)
            #UserMailer.new_information_request_reply_to_comment(current_user, @item, @requirement, user).deliver
          end
        end
      else
        @error = "¡Ha ocurrido un error!"
      end
      respond_to do |format|
        format.js
      end
    end


  end
end

app/controllers/panel/events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class EventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Event
    end

    def permits
      [:justification, :event_start, :document, :user_id ]
    end

    def exportable_fields
      [:name]
    end

    def create
      @item = model.new item_params
      @item.requirements.build unless @item.requirements.any?
      @item.notification_mode = params[:notification_mode] || []
      @item.from_website = false
      @item.confirmed = true
      @item.confirmed_at = Time.current

      if @item.save
        @item.state = "newer"
        #@item.set_reference_code
        #@item.set_correlative

        #@item.delivery_deadline = @information_request.start_date_with_business(10)
        @item.save

        return redirect_to(index_url, flash: { saved: true })
      else
        puts @item.errors.full_messages
        init_form
        breadcrumbs_for(:new)
        render template: 'concerns/panel/form'
      end
    end

    def show
      @item = InformationRequest.find(params[:id]).decorate
      breadcrumbs_for(:show)
      #@allowed_users = User.joins(:roles).where("")
    end

    def get_states
      render json: @states = InformationRequest.states.to_json
    end

    def not_admitted

    end

    def admitted
      @item = InformationRequest.find(params[:id])
      @item.set_reference_code
      @item.set_correlative
      @item.admitted_at = Time.current
      #@item.delivery_deadline = @item.start_date_with_business(10)
      #@item.deliver_information_request_user_notification if information_request.save(validate: false)
      @item.save(validate: false)
      redirect_to panel_information_request_url(@item.id)
    end

    private

    def institutions
      @institutions = current_user.has_role?("admin") ?
      Institution.all.order(:name) :
      Institution.where("id IN (?)", current_user.institution_ids).order(:name)
    end
    helper_method :institutions

    def information_request
      @information_request ||= params[:id] ?
      InformationRequest.find(params[:id]) :
      InformationRequest.new(params[:information_request])
    end
    helper_method :information_request

    def init_form
      @occupations = Occupation.order(:name)
      @states = State.order(:name)
    end

    def nationalities
      @nationalities ||= Nationality.order(:name)
    end
    helper_method :nationalities


  end
end

app/controllers/panel/home_controller.rb
# frozen_string_literal: true
module Panel
  #
  class HomeController < PanelController
    def index
    end
  end
end

app/controllers/panel/information_request_iaip_process_notes_controller.rb
# frozen_string_literal: true
module Panel
  #
  class InformationRequestIaipProcessNotesController < PanelController
    include Panel::Crud
    include Panel::Multiple
    load_and_authorize_resource
    skip_before_filter :verify_authenticity_token
    layout false
    respond_to :html, :js

    def model
      InformationRequestIaipProcessNote
    end

    def permits
      [:content, :note_date, :information_request_iaip_process_id]
    end

    def new
    end

    def create
      @item = model.new item_params
      if @item.save
      else
        @error = "¡Ha ocurrido un error!"
      end
      respond_to do |format|
        format.js
      end
    end


  end
end

app/controllers/panel/information_request_iaip_processes_controller.rb
# frozen_string_literal: true
module Panel
  #
  class InformationRequestIaipProcessesController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      InformationRequestIaipProcess
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'panel/information_request_iaip_processes/index'
    end

    def respond_to_json
      if current_user.admin?
        @q = InformationRequest.closed_requests
      elsif current_user.oir?
        @q = InformationRequest.where("institution_id IN (?)", current_user.institution_ids).closed_requests
      end
      @q = @q.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def json_methods
      [:new_or_existing, :boolean_new_or_existing]
    end

    def new
      @information_request = InformationRequest.find(params[:id])
      @item = model.new
      @item.notes.build

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/information_request_iaip_processes/form'
    end

    def show
      @item = model.find(params[:id]).decorate
      breadcrumbs_for(:show)
      render template: 'panel/information_request_iaip_processes/show'
    end

    def create
      @item = model.new item_params
      return redirect_to(show_url, flash: { saved: true }) if @item.save
      puts @item.errors.full_messages

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/information_request_iaip_processes/form'
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'panel/information_request_iaip_processes/form'
    end

    def update
      respond_to do |format|
        format.json { super }
        format.html do
          return redirect_to(edit_url, flash: { saved: true }) if
            @item.update_attributes(item_params)

          breadcrumbs_for(:edit)
          init_form
          render template: 'panel/information_request_iaip_processes/form'
        end
      end
    end

    def permits
      [:presentation_date, :notification_date, :correlative, :process_type,
      :information_request_id,
      :description, :resolution_result, :resolution_phase, :fullfillment_date,
      :comments, notes_attributes: [:id, :note_date, :content, :_destroy],
      attachments_attributes: [:id, :information_request_iaip_process_id,
      :title, :file, :description, :_destroy]]
    end

    def exportable_fields
      [:name]
    end

  end
end

app/helpers/panel/information_requests_helper.rb
module Panel::InformationRequestsHelper
end

app/views/panel/information_request_iaip_processes/_actions.haml
.row.align-middle
  .columns.small-6
    .actions
      .row.align-stretch
        .columns.shrink

        .columns
          %strong.total-entries{ 'ng-bind' => "total_entries + ' Registros'" }


  .columns.small-18
    %ul.menu.align-right

    .visibility-controls
      = label_tag nil, 'ng-repeat' => 'col in table.cols' do
        %input{ type: :checkbox, ng: { model_options: "{ getterSetter: true }", model: 'col.show' }}
        %span {{ col.title() }}
    %br

app/views/panel/information_request_iaip_processes/_attachment_fields.haml
.nested-fields
  .control
    .row.align-middle.align-justify
      .columns.small-5= f.label "Titulo"
      .columns.small-18= f.text_field :title

  .control
    .row.align-middle.align-justify
      .columns.small-5= f.label "Comentario"
      .columns.small-18= f.text_area :comment, rows: 2
  .control
    .row.align-left
      .columns.small-5.medium-8= f.label :file
      .columns.small-15.medium-10= f.file_field :file
      - if f.object.file.exists?
        .columns.small-4.medium-4
          = link_to f.object.file.url, target: "_blank" do
            %i.material-icons file_download
            = " Descargar"

  .remove-nested
    = link_to_remove_association f do
      %i.material-icons remove_circle_outline
      Remover

app/views/panel/information_request_iaip_processes/_form.haml
%h2
  Proceso en el IAIP

= f.hidden_field :information_request_id, value: f.object.information_request_id.blank? ? params[:id] : f.object.information_request_id

.control.entity_type_dependent
  .row.align-middle.align-justify
    .columns.small-5= f.label :presentation_date
    .columns.small-18= f.date_select :presentation_date, { prompt: { day: 'Día', month: 'Mes', year: 'Año' }, start_year: 2016, end_year: Date.today.year }, class: 'date'

.control.entity_type_dependent
  .row.align-middle.align-justify
    .columns.small-5= f.label :notification_date
    .columns.small-18= f.date_select :notification_date, { prompt: { day: 'Día', month: 'Mes', year: 'Año' }, start_year: 2016, end_year: Date.today.year }, class: 'date'

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :correlative
    .columns.small-18= f.text_field :correlative


.control.entity_type_dependent
  .row.align-middle.align-justify
    .columns.small-5= f.label :process_type
    .columns.small-18= f.select :process_type, model.process_types.keys.map{ |i| [t(i, scope: 'activerecord.enum.information_request_iaip_process.process_type'), i] }, include_blank: true

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :description
    .columns.small-18= f.text_area :description, rows: 2

%br
%h2= "Adjuntos del proceso"
%div
  %i.muted Por favor, incluya, de uno a uno, los adjuntos generados referentes al proceso.
#attachments
  = f.fields_for :attachments do |attachment|
    = render partial: 'attachment_fields', locals: { f: attachment }
  .add-nested
    = link_to_add_association f, :attachments do
      %i.material-icons add_circle_outline
      Agregar
%br


%h2= "Notas del proceso"
%div
  %i.muted Por favor, incluya, de uno a uno, las notas referentes al proceso.
%br
#requirements
  = f.fields_for :notes do |note|
    = render partial: 'note_fields', locals: { f: note }

  .add-nested
    = link_to_add_association f, :notes do
      %i.material-icons add_circle_outline
      Agregar


.control
  .row.align-middle
    .columns.small-5= f.label :resolution_phase
    .columns.small-3
      = f.check_box :resolution_phase, {class: "radio-inline"}, true, false
    .columns.small-15

#fullfillment_date
  .control.entity_type_dependent
    .row.align-middle.align-justify
      .columns.small-5= f.label :fullfillment_date
      .columns.small-18= f.date_select :fullfillment_date, { prompt: { day: 'Día', month: 'Mes', year: 'Año' }, start_year: 2016, end_year: Date.today.year+2 }, class: 'date'

  .control
    .row.align-middle.align-justify
      .columns.small-5= f.label :comments
      .columns.small-18= f.text_area :comments, rows: 2


.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :iaip_resolution
    .columns.small-18= f.select :iaip_resolution, model.iaip_resolutions.keys.map{ |i| [t(i, scope: 'activerecord.enum.information_request_iaip_process.iaip_resolution'), i] }, include_blank: true

.control
  .row.align-middle
    .columns.small-5= f.label :judicial_process
    .columns.small-3
      = f.check_box :judicial_process, {class: "radio-inline"}, true, false

app/views/panel/information_request_iaip_processes/_note_fields.haml
.nested-fields
  .control
    .row.align-middle.align-justify
      .columns.small-5= f.label "Nota"
      .columns.small-18
        = f.text_area :content, class: "tinymce", rows: 2
        = tinymce :theme => "modern", skin: "lightgray", statusbar: false
  .remove-nested
    = link_to_remove_association f do
      %i.material-icons remove_circle_outline
      Remover

app/views/panel/information_request_iaip_processes/_table.haml
%script{ type: 'text/ng-template', id: '/clear-filters.html' }
  .clear-filters
    = link_to nil, 'ng-click' => 'clearFilters($event)' do
      %i.material-icons clear
      Remover filtros

.table-container
  %table{ ng: { table: 'table.tableParams', table_columns_binding: 'table.cols' }}
    %tr{ ng: { repeat: 'item in $data' }}
      %td{ data: { title: '', filter: "{ actions: '/clear-filters.html' }" }}
        .action-buttons
          = link_to "{{item.new_or_existing}}", class: 'text-primary' do
            %i.material-icons build
            Proceso en IAIP

      %td{ data: { title: "'¿Posee proceso en IAIP?'" }, 'ng-if' => 'true', sortable: "'iaip_process_kind'" } {{ item.iaip_process_kind }}

      %td{ data: { title: "'Estado'" }, 'ng-if' => 'true', sortable: "'state'" } {{ item.state }}
      %td{ data: { title: "'Correlativo'" }, 'ng-if' => 'true', filter: "{ correlative_icont: 'text' }", sortable: "'correlative'" } {{ item.correlative }}

      %td{ data: { title: "'Institución'" }, 'ng-if' => 'true', filter: "{ institution_id_eq: 'select' }", 'filter-data' => "getSelectList('institutions')", sortable: "'institution_name'" } {{ item.institution_id }}

      - unless current_user.has_role?("administrative_unit")
        %td{ data: { title: "'Nombre'" }, 'ng-if' => 'true', filter: "{ firstname_or_lastname_icont: 'text' }", sortable: "'lastname'" } {{ item.firstname }} {{item.lastname}}
      %td{ data: { title: "'Fecha de ingreso'" }, 'ng-if' => 'true', filter: "table.dateFilter('confirmed_at')", sortable: "'confirmed_at'" } {{ item.confirmed_at | date:'dd/MM/yy hh:mm a' }}
      %td{ data: { title: "'Procesada'" }, 'ng-if' => 'true', filter: "table.dateFilter('admitted_at')", sortable: "'admitted_at'" } {{ item.admitted_at | date:'dd/MM/yyyy hh:mm a' }}

app/views/panel/information_request_iaip_processes/form.haml
.header
  .row.align-middle
    .columns
      %h1
        %i.material-icons input
        = t model.to_s.underscore, scope: 'activerecord.models', count: 1
    .columns.shrink


.breacrumb
  = render_breadcrumbs separator: ' / '

.wrapper
  .row.align-center
    .columns.large-20
      .container
        - if @item.errors.any?
          .alert-msg.error
            No se pudo guardar el registro, por favor, revise los campos del formulario

        - if flash[:saved]
          .alert-msg.success
            Registro guardado correctamente

        = form_for [:panel, @item], as: :item, html: { :multipart => true, class: "requirement-comment-form" } do |f|
          .form

            = render partial: 'form', locals: { f: f }

            .control
              .row.align-center.align-justify
                .columns.small-5
                .columns.small-18
                  = f.button class: "hollow button success", type: :submit do
                    %i.material-icons save
                    Guardar

app/views/panel/information_request_iaip_processes/index.haml
%section{ ng: { controller: 'tableController as table' }}
  .header
    .row.align-middle
      .columns
        %h1
          %i.material-icons list
          = t model.to_s.underscore, scope: 'activerecord.models', count: :many
      .columns.shrink

  .breacrumb
    = render_breadcrumbs separator: ' / '

  .container

    - if flash[:destroyed]
      .alert-msg.success
        Registro eliminado correctamente

    = render partial: 'actions'
    = render partial: 'table'

app/views/panel/information_request_iaip_processes/show.haml
.header
  .row.align-middle
    .columns
      %h1
        %i.material-icons input
        = t model.to_s.underscore, scope: 'activerecord.models', count: 2
    .columns.shrink
      - unless @item.new_record?


        = link_to edit_panel_information_request_iaip_process_url do
          %i.material-icons add_circle_outline
          %br
          Editar

        -# link_to url_for(action: :destroy), method: :delete, data: { confirm: '¿Está seguro?' } do
          %i.material-icons.danger delete
          %br
          Eliminar

.breacrumb
  = render_breadcrumbs separator: ' / '

%section.info-request-tool
  .container
    .row
      .small-12
        %h2 Información del proceso
    .row

      .small-12.columns
        .table
          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Correlativo de la solicitud
            .columns.small-24.medium-14.large-14
              = @item.information_request.correlative rescue " - "

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Fecha de presentación de escrito de ciudadano
            .columns.small-24.medium-14.large-14
              =  l @item.presentation_date, format: :localized rescue t('undefined')

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Fecha de notificación del IAIP a OIR
            .columns.small-24.medium-14.large-14
              =  l @item.notification_date, format: :localized rescue t('undefined')

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Correlativo (asignado por IAIP)
            .columns.small-24.medium-14.large-14
              = @item.correlative

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Tipo de procedimiento
            .columns.small-24.medium-14.large-14
              = @item.process_type

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Descripción del caso
            .columns.small-24.medium-14.large-14
              = @item.description

      .small-12.columns
        .table.no-border.no-margin
          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Resultado de la resolución
            .columns.small-24.medium-14.large-14
              = @item.iaip_resolution

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong ¿Existe un proceso en el órgano judicial?
            .columns.small-24.medium-14.large-14
              = @item.judicial_process

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong ¿Existe una fase de cumplimiento?
            .columns.small-24.medium-14.large-14
              = @item.resolution_phase

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Fecha de notificación al IAIP sobre el cumplimiento
            .columns.small-24.medium-14.large-14
              =  l @item.fullfillment_date, format: :localized rescue t('undefined')

          .row.align-justify
            .columns.small-24.medium-10.large-10
              %strong Observaciones
            .columns.small-24.medium-14.large-14
              = @item.comments
  %hr
  %br
  .container
    .row
      .small-20
        %h2 Adjuntos del proceso
    .row
      .small-16
        - if @item.attachments.size > 0
          - @item.attachments.each_with_index do |attachment, index|
            %div{class: "#{index%2==0 ? 'comment-par': 'comment-even'}"}
              .row.align-justify
                .columns.medium-18.small-18
                  %h5
                    = "Publicado el #{l attachment.created_at, format: :localized2}"
                  .message-wrap
                    = attachment.title rescue "Adjunto"
                  .message-wrap
                    = attachment.comment rescue nil
                .columns.small-4.medium-4
                  = link_to attachment.file.url, target: "_blank" do
                    %i.material-icons file_download
                    = " Descargar"

  %br
  .container
    .row
      .small-20
        %h2 Notas del proceso
    .row
      .small-16
        - if @item.notes.size > 0
          - @item.notes.each_with_index do |comment, index|
            %div{class: "#{index%2==0 ? 'comment-par': 'comment-even'}"}
              .row.align-justify
                .columns.medium-24.small-24
                  %h5
                    = "Publicado el #{l comment.created_at, format: :localized2}"
              .row.align-justify
                .columns.medium-18.small-24
                  .message-wrap
                    = comment.content.html_safe