config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'panel/home#index'
  #root to: 'information_requests#index'

  %w(404 422 500 503).each do |code|
    get code, to: 'errors#show', code: code
  end


  resources :information_requests, only: [:index, :create, :new] do
    collection do
      get 'confirm'
      get 'new_personal'
      post 'create_personal'
      get 'please_confirm'
      get 'terms'
    end
  end

  namespace :panel do
    root to: 'home#index'

    resources :profile, only: [:edit, :update]
    resources :versions, only: [:show]

    resources :admin_settings, only: [] do
      put :table_columns, on: :collection
    end

    resources :institution_calendars, only: [:index, :show, :new, :create] do
      resources :calendar_events, except: [:show, :index]
    end

    resources :information_request_iaip_processes

    resources :information_requests do
      member do
        get 'admitted'
        get 'not_admitted'
        put 'process_request'
        get 'closure'
        put 'close_request'
        get 'download_request'
        get 'download_documents'
        put 'admit_date'
        post 'tags'
        get 'edit_personal'
        put 'update_personal'

        resources :information_request_iaip_processes, except: [:index]
      end
      collection do
        put 'updates'
        put 'destroys'
        get 'list'
        get 'get_states'
        get 'statistics'
        get 'basic_csv_export'
        get 'advanced_csv_export'
        get 'new_personal'
        post 'create_personal'
      end

    end

    resources :requirements do
      member do
        put 'management'
      end
    end

    resources :comments

    [
      :institutions,
      :oir_addresses,
      :users,
      :occupations,
      :events,
      :institution_schedules,
      :information_request_records
    ].each do |resource|
      resources resource do
        put :updates, on: :collection
        put :destroys, on: :collection
        get :list, on: :collection
      end
    end
  end

  namespace :api do
    resources :dropdowns do
      member do
        get :state_cities
      end
    end

    resources :information_requests do
      collection do
        get :controls
      end
    end
  end

end

app/controllers/concerns/panel/crud.rb
# frozen_string_literal: true
module Panel
  #
  module Crud
    extend ActiveSupport::Concern

    included do
      respond_to :html
      before_action :set_item, only: [:show, :edit, :update, :destroy]
      before_action :set_uniq_institution!, only: [:update]

      helper_method :model
    end

    def index
      respond_to do |format|
        format.json { super }
        format.csv  { super }
        format.html { respond_to_html }
      end
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'concerns/panel/index'
    end

    def new
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def create
      @item = model.new item_params
      set_uniq_institution!
      return redirect_to(edit_url, flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'concerns/panel/form'
    end

    def update
      respond_to do |format|
        format.json { super }
        format.html do
          return redirect_to(edit_url, flash: { saved: true }) if
            @item.update_attributes(item_params)

          breadcrumbs_for(:edit)
          init_form
          render template: 'concerns/panel/form'
        end
      end
    end

    def destroy
      @item.destroy
      redirect_to index_url, flash: { destroyed: true }
    end

    def init_form
    end

    def set_uniq_institution!
      return unless @item.respond_to? :institution_id
      #return unless current_user.one_institution?
      @item.institution_id = current_user.uniq_institution.try(:id)
    end

    private

    def item_params
      perms = params.require(:item).permit(permits)
      #perms.delete(:institution_id) if current_user.one_institution?
      perms
    end

    def set_item
      @item = if model.respond_to?(:friendly)
                model.friendly.find params[:id]
              else
                model.find params[:id]
              end
    end

    def edit_url
      url_for(action: :edit, id: @item)
    end

    def show_url
      url_for(action: :show, id: @item)
    end

    def index_url
      url_for(controller: model.to_s.underscore.pluralize, action: :index)
    end

    def humanized_model_name(count = 1)
      t(model.to_s.underscore, scope: 'activerecord.models', count: count)
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(count: :many), index_url
      add_breadcrumb t(action.to_s), nil
    end
  end
end

app/controllers/concerns/panel/multiple.rb
# frozen_string_literal: true
module Panel
  #
  module Multiple
    extend ActiveSupport::Concern

    included do
      respond_to :json

      before_action :ngtable_to_rails_filter_param, only: [:index]
      before_action :ngtable_to_rails_sort_param,   only: [:index]
    end

    def update
      respond_to do |format|
        format.html { super }
        format.json do
          sleep 0.5

          return render json: { success: true } if
            @item.update_attributes(item_params)

          render json: { success: false }
        end
      end
    end

    def updates
      model.where(id: params[:ids]).each do |item|
        item.assign_attributes(item_params.to_hash)
        item.save(validate: false)
      end
    end

    def destroys
      model.where(id: params[:ids]).each(&:destroy)
    end

    def index
      respond_to do |format|
        format.html { super }
        format.csv  { super }
        format.json { respond_to_json }
      end
    end

    def respond_to_json
      @q = model.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def json_result(collection)
      {
        result:        json_parsed(collection),
        total_entries: collection.total_entries,
        admin_setting: current_user.admin_setting
      }
    end

    def json_parsed(c)
      c.decorate.as_json(include: json_includes, methods: json_methods)
    end

    def json_includes
      nil
    end

    def json_methods
      nil
    end

    def list
      render json: model
        .select(:id, model.acts_as_label)
        .order(model.acts_as_label)
        .to_json
    end

    private

    def ngtable_to_rails_filter_param
      return unless params.key?(:filter)
      params[:filter]
        .update(params[:filter]) { |_k, v| URI.decode(v) }
        .delete_if { |_k, v| v == 'null' }
    end

    def ngtable_to_rails_sort_param
      return unless params.key?(:sorting)

      params[:filter] ||= {}
      params[:filter][:s] = params[:sorting].flatten.join(' ')
    end
  end
end

app/controllers/panel/admin_settings_controller.rb
# frozen_string_literal: true
module Panel
  #
  class AdminSettingsController < PanelController
    before_action :fetch_admin_setting

    def table_columns
      @admin_setting.update_table_columns(item_params[:table_columns])
    end

    # private

    def item_params
      params.require(:admin_setting).tap do |whitelisted|
        whitelisted[:table_columns] = params[:admin_setting][:table_columns]
      end
    end

    def fetch_admin_setting
      @admin_setting = AdminSetting
                       .where(admin_id: current_admin.id)
                       .first_or_create
    end
  end
end

app/controllers/panel/calendar_events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CalendarEventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      CalendarEvent
    end

    def new
      @institution_calendar = InstitutionCalendar.find(params[:institution_calendar_id])
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/calendar_events/form'
    end

    def edit
      @item = CalendarEvent.find(params[:id])
      @institution_calendar = @item.institution_calendar

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/calendar_events/form'
    end

    def create
      @item = model.new item_params
      @item.user_id = current_user.id
      #@item.institution_calendar_id = params[:institution_calendar_id]
      return redirect_to(edit_panel_institution_calendar_calendar_event_url(@item.institution_calendar_id, @item.id), flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/calendar_events/form'
    end

    def update
      @item = CalendarEvent.find(params[:id])
      @institution_calendar = @item.institution_calendar
      return redirect_to(edit_panel_institution_calendar_calendar_event_url(@item.institution_calendar_id, @item.id), flash: { saved: true }) if @item.update_attributes(item_params)
      init_form
      breadcrumbs_for(:new)
      render template: 'panel/calendar_events/form'
    end

    def destroy
      @item = CalendarEvent.find(params[:id])
      @institution_calendar = @item.institution_calendar
      @item.destroy
      redirect_to panel_institution_calendar_url(@institution_calendar), flash: { destroyed: true }
    end

    def permits
      [:name, :description, :kind, :event_date, :repetitive, :institution_calendar_id]
    end

    def exportable_fields
      [:name]
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'panel/calendar_events/index'
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb "Listado de eventos", panel_institution_calendar_url(params[:institution_calendar_id])
      add_breadcrumb t(action.to_s), nil
    end

  end
end

app/controllers/panel/comments_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CommentsController < PanelController
    include Panel::Crud
    include Panel::Multiple
    load_and_authorize_resource
    skip_before_filter :verify_authenticity_token
    layout false
    respond_to :html, :js

    def model
      Comment
    end

    def permits
      [:message, :document, :requirement_id]
    end

    def exportable_fields
      [:message, :document]
    end

    def new
    end

    def create
      @requirement = Requirement.find(params[:item][:requirement_id])
      @item = model.new item_params
      @item.user_id = current_user.id
      if @item.save
        @users = User.where(id: @requirement.assigned_users) rescue nil
        @users = @users - [current_user] rescue nil
        if @users
          @users.each do |user|
            UserMailer.delay.new_information_request_reply_to_comment(current_user, @item, @requirement, user)
            #UserMailer.new_information_request_reply_to_comment(current_user, @item, @requirement, user).deliver
          end
        end
      else
        @error = "¡Ha ocurrido un error!"
      end
      respond_to do |format|
        format.js
      end
    end


  end
end

app/controllers/panel/events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class EventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Event
    end

    def permits
      [:justification, :event_start, :document, :user_id ]
    end

    def exportable_fields
      [:name]
    end

    def create
      @item = model.new item_params
      @item.requirements.build unless @item.requirements.any?
      @item.notification_mode = params[:notification_mode] || []
      @item.from_website = false
      @item.confirmed = true
      @item.confirmed_at = Time.current

      if @item.save
        @item.state = "newer"
        #@item.set_reference_code
        #@item.set_correlative

        #@item.delivery_deadline = @information_request.start_date_with_business(10)
        @item.save

        return redirect_to(index_url, flash: { saved: true })
      else
        puts @item.errors.full_messages
        init_form
        breadcrumbs_for(:new)
        render template: 'concerns/panel/form'
      end
    end

    def show
      @item = InformationRequest.find(params[:id]).decorate
      breadcrumbs_for(:show)
      #@allowed_users = User.joins(:roles).where("")
    end

    def get_states
      render json: @states = InformationRequest.states.to_json
    end

    def not_admitted

    end

    def admitted
      @item = InformationRequest.find(params[:id])
      @item.set_reference_code
      @item.set_correlative
      @item.admitted_at = Time.current
      #@item.delivery_deadline = @item.start_date_with_business(10)
      #@item.deliver_information_request_user_notification if information_request.save(validate: false)
      @item.save(validate: false)
      redirect_to panel_information_request_url(@item.id)
    end

    private

    def institutions
      @institutions = current_user.has_role?("admin") ?
      Institution.all.order(:name) :
      Institution.where("id IN (?)", current_user.institution_ids).order(:name)
    end
    helper_method :institutions

    def information_request
      @information_request ||= params[:id] ?
      InformationRequest.find(params[:id]) :
      InformationRequest.new(params[:information_request])
    end
    helper_method :information_request

    def init_form
      @occupations = Occupation.order(:name)
      @states = State.order(:name)
    end

    def nationalities
      @nationalities ||= Nationality.order(:name)
    end
    helper_method :nationalities


  end
end

app/controllers/panel/home_controller.rb
# frozen_string_literal: true
module Panel
  #
  class HomeController < PanelController
    def index
    end
  end
end

app/controllers/panel/information_request_iaip_process_notes_controller.rb
# frozen_string_literal: true
module Panel
  #
  class InformationRequestIaipProcessNotesController < PanelController
    include Panel::Crud
    include Panel::Multiple
    load_and_authorize_resource
    skip_before_filter :verify_authenticity_token
    layout false
    respond_to :html, :js

    def model
      InformationRequestIaipProcessNote
    end

    def permits
      [:content, :note_date, :information_request_iaip_process_id]
    end

    def new
    end

    def create
      @item = model.new item_params
      if @item.save
      else
        @error = "¡Ha ocurrido un error!"
      end
      respond_to do |format|
        format.js
      end
    end


  end
end

app/controllers/panel/information_request_iaip_processes_controller.rb
# frozen_string_literal: true
module Panel
  #
  class InformationRequestIaipProcessesController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      InformationRequestIaipProcess
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'panel/information_request_iaip_processes/index'
    end

    def respond_to_json
      if current_user.admin?
        @q = InformationRequest.closed_requests
      elsif current_user.oir?
        @q = InformationRequest.where("institution_id IN (?)", current_user.institution_ids).closed_requests
      end
      @q = @q.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def json_methods
      [:new_or_existing, :boolean_new_or_existing]
    end

    def new
      @information_request = InformationRequest.find(params[:id])
      @item = model.new
      @item.notes.build

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/information_request_iaip_processes/form'
    end

    def show
      @item = model.find(params[:id]).decorate
      breadcrumbs_for(:show)
      render template: 'panel/information_request_iaip_processes/show'
    end

    def create
      @item = model.new item_params
      return redirect_to(show_url, flash: { saved: true }) if @item.save
      puts @item.errors.full_messages

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/information_request_iaip_processes/form'
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'panel/information_request_iaip_processes/form'
    end

    def update
      respond_to do |format|
        format.json { super }
        format.html do
          return redirect_to(edit_url, flash: { saved: true }) if
            @item.update_attributes(item_params)

          breadcrumbs_for(:edit)
          init_form
          render template: 'panel/information_request_iaip_processes/form'
        end
      end
    end

    def permits
      [:presentation_date, :notification_date, :correlative, :process_type,
      :information_request_id,
      :description, :resolution_result, :resolution_phase, :fullfillment_date,
      :comments, notes_attributes: [:id, :note_date, :content, :_destroy],
      attachments_attributes: [:id, :information_request_iaip_process_id,
      :title, :file, :description, :_destroy]]
    end

    def exportable_fields
      [:name]
    end

  end
end

app/views/panel/requirements/_add_requirement.haml
%h2
  Agregar nuevo requerimiento

.control
  .row.align-middle.align-justify
    .columns.medium-4.small-24
      = f.label "Nuevo Requerimiento"
    .columns.medium-15.small-22
      = f.text_area :requested_information, class: "tinymce", rows: 2
      = tinymce :theme => "modern", skin: "lightgray", statusbar: false
    .columns.medium-5.hide-for-small-only
      = f.button class: "hollow button success", type: :submit, data: { disable_with: "Por favor espere..."} do
        %i.material-icons save
        Guardar
.control.show-for-small-only
  .row.align-right
    .columns.small-24
      = f.button class: "hollow button success", type: :submit, data: { disable_with: "Por favor espere..."} do
        %i.material-icons save
        Guardar

app/views/panel/requirements/_close_requirement.haml
%br
.columns.medium-24.small-24.close-requirement-tag
  .row.align-middle
    .medium-24.columns
      = label_tag "", class: "radio-inline" do
        = label_tag "¿Cerrar requerimiento? "
        = check_box_tag("close_requirement", true, false, {id: "close-requirement-check-#{requirement.id}"})



%div{id: "close-requirement-justification-#{requirement.id}", class: "close-requirement-justification columns medium-24 small-24"}

  .control
    .row.align-middle
      .medium-24.columns
        = f.label :information_type
        = f.select :information_type, options_for_select(InformationRequest::INFORMATION_TYPE.invert), { include_blank: t('helpers.select.prompt'), class: 'resolution_type' }, id: "item_information_type_#{requirement.id}"

  .control
    .row.align-middle
      .medium-24.columns
        = f.label :resolution_type
        = f.select :resolution_type, grouped_options_for_select(InformationRequest::RESOLUTION_TYPE), { include_blank: t('helpers.select.prompt'), class: 'resolution_type' }, id: "item_resolution_type_#{requirement.id}"

  :javascript
      $(function(){
        justifications = $("#item_resolution_type_#{requirement.id}").html();
        $('#item_resolution_type_#{requirement.id} optgroup').remove();
        $('#item_information_type_#{requirement.id}').change(function(){

          type = $('#item_information_type_#{requirement.id} :selected').text();
          options = $(justifications).filter("optgroup[label='" + type + "']").html();
          $('#item_resolution_type_#{requirement.id} option:gt(0)').remove();
          if ( options )
            $('#item_resolution_type_#{requirement.id}').append(options);
        });
      });


  .control
    .row.align-middle.align-justify
      .columns.medium-5= label_tag "Fecha: "
      .columns.medium-18
        = hidden_field_tag "event_start", value: Date.current
        = hidden_field_tag "user_id", value: current_user.id
        = hidden_field_tag "state", value: 'closed_requirement'
        = l(Date.current, format: :default)

  .control
    .row.align-middle.align-justify
      .columns.medium-5= label_tag "Justificación: "
      .columns.medium-18= text_area_tag "justification", nil, {rows: 2, class: "close-requirement-justification-#{requirement.id}"}

  .control
    .row.align-middle.align-justify
      .columns.medium-5= label_tag "Documento: "
      .columns.medium-18
        = f.file_field :file
        %br
        %i.muted
          = t('activerecord.attributes.information_request.document_image_max_size')
          ,
          = t('activerecord.attributes.information_request.document_image_extensions')

app/views/panel/requirements/management.js.erb
<% if @error %>
  $("#requirement-message-<%=@requirement.id%>")
  .html('<div class="alert-msg error"">Ha ocurrido un error</div>');
  $(".alert-msg").click(function(){
    $(this).fadeOut("slow", function(){});
  });
<% else %>
  // Si se guarda correctament
  $("#requirement-message-<%=@requirement.id%>")
  .html('<div class="alert-msg success">Informacion guardada correctamente</div>');
  $(".alert-msg").click(function(){
    $(this).fadeOut("slow", function(){});
  });
  // Si el requerimiento no cumple con fondo
  <% if @requirement.meets_depth == true && !@requirement.closed? %>

    $(".requirement-tool-<%=@requirement.id%>").css("background-color", "#2196f3");
    $("#requirement-message-<%=@requirement.id%>").closest(".callout").css("background-color", "#DEF2F8");

  <% elsif @requirement.meets_depth == false && !@requirement.closed?%>
    $(".requirement-tool-<%=@requirement.id%>").css("background-color", "#FFAE00");
    $("#requirement-message-<%=@requirement.id%>").closest(".callout").css("background-color", "#F6E0B2");
  <% end %>

  // Si los requerimientos están cerrados
  <% if @information_request.all_requirements_are_closed? and @information_request.process?  %>
    $(".menu.align-right").html('<li>'+
    '<a href="<%=closure_panel_information_request_url(@information_request)%>"'
    + ' id="close-request" class="separated-list button secondary">'
    + '<i class="material-icons">stop</i><span>Cerrar solicitud</span</a>'
    + '</li>');
  <% end %>

  // Mensaje con el arreglo de usuarios asignados al requerimiento
  <% if @requirement.has_assigned_users? %>
    $(".requirements_with_assigned_users-<%=@requirement.id%>")
    .html('<div class="callout primary">'
    + '<h2>Asignado a: <%=@requirement.show_assigned_users%></h2>'
    + '<br>Asignado el: <%=l(@requirement.assigned_date, format: :localized)%>, '
    + 'Última actualización: <%=l(@requirement.assigned_date_update, format: :localized)%></div>');
  <% end  %>


  // Se inicializa de nuevo el formulario
  <%
    form_for @requirement, as: :item,
    url: management_panel_requirement_url(@requirement.id),
    html: { remote: true, method: :put,
      id: "requirement-#{@requirement.id}" } do |f|
      @builder = f
    end
  %>

  // Si el requerimiento debe ser cerrado por cumplir Art. 74B de la LAIP
  <% if !@requirement.meets_depth.nil? and !@requirement.art_74_laip.nil? and @requirement.art_74_laip == true %>

    $("form#requirement-<%=@requirement.id%>").hide();
    $("#requirement-closed-<%=@requirement.id%>")
    .append("<div class='callout warning'>Requerimiento cerrado por articulo 74-B de la LAIP.</div></br>");
    $("form#requirement-comment-form-<%=@requirement.id%>").hide();

  // Si algun requerimiento no cumple con fondo se activa el boton de prevenir
  <% elsif !@requirement.meets_depth.nil? and @requirement.meets_depth == false and !@requirement.closed?%>
    $(".menu.align-right").html('');

    <% if @information_request.can_correct? %>
      $(".menu.align-right").html('');
      $(".menu.align-right").html('<li><a href="#" id="correct-request" '
      + ' class="separated-list button warning"> '
      + ' <i class="material-icons">pause</i> '
      + ' <span>Prevenir solicitud</span</a></li>');
      $("#close-requirement-<%=@requirement.id%>")
      .html("<%= j render(partial: 'panel/requirements/close_requirement', locals: {f: @builder, requirement: @requirement}) %>");
    <% else %>
      $(".menu.align-right").html('');
      $(".cannot-do-action").show();
    <% end %>

    <% if (@information_request.correct? && !@requirement.closed?)%>
      console.log("puede subsanar o no")
      $(".menu.align-right").html('<li><a href="#" id="process-request" '
      + ' class="separated-list button primary"> '
      + ' <i class="material-icons">play_arrow</i> '
      + ' <span>Subsanar solicitud</span></a></li> '
      + ' <li><a href="#" id="not-corrected-request" '
      + ' class="separated-list button secondary"> '
      + ' <i class="material-icons">stop</i> '
      + ' <span>No subsanar solicitud</span></a></li> ');

      $(".cannot-do-action").show();
      $("#close-requirement-<%=@requirement.id%>")
      .html("<%= j render(partial: 'panel/requirements/close_requirement', locals: {f: @builder, requirement: @requirement}) %>");

    <% end %>

  // Si el requerimiento ya está cerrado
  <% elsif @requirement.closed? %>
    $(".cannot-do-action").hide();
    $("form#requirement-<%=@requirement.id%>").hide();
    $("form#requirement-comment-form-<%=@requirement.id%>").hide();

  //
  <% else %>
    $(".menu.align-right").html('');

    <% if @information_request.can_correct? %>
      $(".menu.align-right").html('');
      $(".menu.align-right").html('<li><a href="#" id="correct-request" '
      + ' class="separated-list button warning"> '
      + ' <i class="material-icons">pause</i> '
      + ' <span>Prevenir solicitud</span</a></li>');
      $("#close-requirement-<%=@requirement.id%>")
      .html("<%= j render(partial: 'panel/requirements/close_requirement', locals: {f: @builder, requirement: @requirement}) %>");
    <% else %>
      $(".menu.align-right").html('');
      $(".cannot-do-action").show();
    <% end %>

    <% if @information_request.can_process? or @information_request.correct? %>
      $(".menu.align-right").html('<li><a href="#" id="process-request" '
      + ' class="separated-list button primary"> '
      + ' <i class="material-icons">play_arrow</i> '
      + ' <span><%=@information_request.correct? ? t('resume_request') : t('admit_request')%>'
      + ' </span></a></li> ');
      <% if @information_request.correct? %>
        $(".menu.align-right").append('<li><a href="#" id="not-corrected-request" '
        + ' class="separated-list button secondary"> '
        + ' <i class="material-icons">stop</i> '
        + ' <span>No subsanar solicitud</span></a></li> ');
      <% end %>
    <% end %>

    <% if @information_request.process? and @information_request.can_extended? %>
      $(".menu.align-right").html('');
      $(".menu.align-right").html('<li><a href="#" id="extended-request" '
      + ' class="separated-list button warning"> '
      + ' <i class="material-icons">schedule</i> '
      + ' <span><%=t("extend_request")%>');

    <% end %>

    $(".cannot-do-action").hide();
    $("#close-requirement-<%=@requirement.id%>")
    .html("<%= j render(partial: 'panel/requirements/close_requirement', locals: {f: @builder, requirement: @requirement}) %>");

    $('#requirement-<%=@requirement.id%>').validate();
    $('#close-requirement-check-<%=@requirement.id%>').click(function(e) {
      if ($('#close-requirement-check-<%=@requirement.id%>').is(':checked')) {
        $("#close-requirement-justification-<%=@requirement.id%>").show();
        $('#item_resolution_type').rules('add', {
          required: true
        });
        $('.close-requirement-justification-<%=@requirement.id%>').rules('add', {
          required: true
        });
      }
      else {
        $("#close-requirement-justification-<%=@requirement.id%>").hide();
        $('#item_resolution_type').rules('add', {
          required: false
        });
        $('.close-requirement-justification-<%=@requirement.id%>').rules('add', {
          required: false
        });
      }
    });
  <% end %>
<% end %>

// Reload MANUALLY

$('#correct-request').on("click", function(e) {
  e.stopPropagation();
  e.preventDefault();
  return $('.correct-form').toggle();
});

$("#process-request").on("click", function(e) {
  e.stopPropagation();
  e.preventDefault();
  return $('.process-form').toggle();
});

$("#extended-request").on("click", function(e) {
  e.stopPropagation();
  e.preventDefault();
  return $('.extended-form').toggle();
});